local:
  output_dir: '<full path to output directory for timeline tweets>'
twitter:
  account:
    bearer_token: '<your twitter api bearer token>'
  # Can ignore these unless you would like to change the information retreived from twitter.
  # See https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets
  #   and https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users
  query_params:
#    expansions:
#    media_fields:
#    place_fields:
#    poll_fields:
    tweet_fields:
      - author_id
      - conversation_id
      - created_at
      - in_reply_to_user_id
      - lang
      - public_metrics
      - possibly_sensitive
      - referenced_tweets
      - reply_settings
      - source
      - text
      - withheld
    user_fields:
      - created_at
      - description
      - id
      - name
      - public_metrics
      - username